export const LLM_BOX_MESSAGE_TYPES = {
  EDITOR_FILE_OPEN: 'EDITOR_FILE_OPEN',
  EDITOR_CONTENT_CHANGED: 'EDITOR_CONTENT_CHANGED',
  EDITOR_SELECTION_CHANGED: 'EDITOR_SELECTION_CHANGED',
  LLM_CONVERSATION_LOAD: 'LLM_CONVERSATION_LOAD',
  LLM_CONVERSATION_SAVE: 'LLM_CONVERSATION_SAVE',
  GET_CURRENT_FILE_INFO: 'GET_CURRENT_FILE_INFO',

  // === Agent 文件操作消息 ===
  AGENT_FILE_READ: 'AGENT_FILE_READ',
  AGENT_FILE_WRITE: 'AGENT_FILE_WRITE',
  AGENT_FILE_CREATE: 'AGENT_FILE_CREATE',
  AGENT_FILE_DELETE: 'AGENT_FILE_DELETE',
  AGENT_FILE_LIST: 'AGENT_FILE_LIST',
  AGENT_FILE_SEARCH: 'AGENT_FILE_SEARCH',
  AGENT_FILE_SEARCH_IN: 'AGENT_FILE_SEARCH_IN',

  // === Agent 状态同步 ===
  AGENT_GET_ROOT_URI: 'AGENT_GET_ROOT_URI',
  AGENT_GET_ACTIVE_FILE_URI: 'AGENT_GET_ACTIVE_FILE_URI',

  // === Agent 上下文持久化 ===
  AGENT_CONTEXT_LOAD: 'AGENT_CONTEXT_LOAD',
  AGENT_CONTEXT_SAVE: 'AGENT_CONTEXT_SAVE',

  // === Agent 执行状态持久化 ===
  AGENT_EXECUTION_STATE_LOAD: 'AGENT_EXECUTION_STATE_LOAD',
  AGENT_EXECUTION_STATE_SAVE: 'AGENT_EXECUTION_STATE_SAVE',
  AGENT_EXECUTION_STATE_DELETE: 'AGENT_EXECUTION_STATE_DELETE',
} as const;
