export const LLM_BOX_MESSAGE_TYPES = {
  EDITOR_FILE_OPEN: 'EDITOR_FILE_OPEN',
  EDITOR_CONTENT_CHANGED: 'EDITOR_CONTENT_CHANGED',
  EDITOR_SELECTION_CHANGED: 'EDITOR_SELECTION_CHANGED',
  LLM_CONVERSATION_LOAD: 'LLM_CONVERSATION_LOAD',
  LLM_CONVERSATION_SAVE: 'LLM_CONVERSATION_SAVE',
  GET_CURRENT_FILE_INFO: 'GET_CURRENT_FILE_INFO',
} as const;
